
POST http://localhost:8080/brand
Content-Type: application/json

{
    "brand_name": "Samsung"
}
### Test Create brand endpoint

POST http://localhost:8080/product
Content-Type: application/json

{
    "product_name": "Kompor 2 TK 709 C (TF)",
    "brand_id": 5,
    "price":1100000
}
### Test Create product endpoint

POST http://localhost:8080/order
Content-Type: application/json

{
    "product_id": 2,
    "price": 1500000,
    "qty": 2
}
### Test Create Order endpoint

GET http://localhost:8080/product?id=5
### Test Get Product By id

GET http://localhost:8080/product/brand?id=5
### Test Get Product By id

GET http://localhost:8080/order?id=2
### Test Get Order by Order Id
